book:
  mysql:
    server-host: localhost
    port: 3306
    username: root
    password: 123123
    database: spring_book_test
  framework:
    base:
      snowflake:
        worker-id: 1
        data-center-id: 2

# Spring 的配置
spring:
  #数据库连接的相关配置
  datasource:
    # 数据库访问配置
    # 主数据源，默认的
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${book.mysql.server-host}:${book.mysql.port}/${book.mysql.database}?characterEncoding=utf-8&useSSL=false
    username: ${book.mysql.username}
    password: ${book.mysql.password}

#设置mybatis
mybatis:
  #  type-aliases-package: com.bcdbook.data.mapper.model
  mapper-locations: classpath:mapper/*/*.xml
  configuration:
    #开启驼峰命名法的匹配
    mapUnderscoreToCamelCase: true


logging:
  level:
    com.bcdbook.framework.base.data.mybatis.test.mapper: trace

#mappers 多个接口时逗号隔开
#mapper.mappers=tk.mybatis.mapper.common.Mapper
mapper:
  mappers: com.bcdbook.framework.base.mapper.BaseMapper
  not-empty: false
  identity: MYSQL
  style: camelhump

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql