book:
  mysql:
    server-host: localhost
    port: 3306
    username: root
    password: 123123
    database: spring_book_test
  framework:
    base:
      snowflake:
        worker-id: 1
        data-center-id: 2

# Spring 的配置
spring:
  #数据库连接的相关配置
  datasource:
    # 数据库访问配置
    # 主数据源，默认的
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${book.mysql.server-host}:${book.mysql.port}/${book.mysql.database}?characterEncoding=utf-8&useSSL=false
    username: ${book.mysql.username}
    password: ${book.mysql.password}