spring:
  # 使用的配置文件
  profiles:
    active: summer
  # 邮件的配置
  mail:
    # 服务主机
    host: ${easy-spring.message.email.host}
    # 用户名
    username: ${easy-spring.message.email.username}
    # 密码
    password: ${easy-spring.message.email.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  # redis 的相关配置
  redis:
    host: ${easy-spring.redis.server-host}
    port: ${easy-spring.redis.port}
    password: ${easy-spring.redis.passowrd}
    database: 0
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
    timeout: 3000ms