-- MySQL Script generated by MySQL Workbench
-- Wed Jan 16 11:21:39 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema easy_spring_security_demo
-- -----------------------------------------------------
-- spring Security demo database
DROP SCHEMA IF EXISTS `easy_spring_security_demo` ;

-- -----------------------------------------------------
-- Schema easy_spring_security_demo
--
-- spring Security demo database
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `easy_spring_security_demo` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `easy_spring_security_demo` ;

-- -----------------------------------------------------
-- Table `easy_spring_security_demo`.`sys_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `easy_spring_security_demo`.`sys_user` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `easy_spring_security_demo`.`sys_user` (
  `id` BIGINT(8) UNSIGNED NOT NULL COMMENT '主键',
  `username` VARCHAR(64) NOT NULL COMMENT '用户名',
  `password` VARCHAR(64) NOT NULL COMMENT '密码',
  `open_id` VARCHAR(45) NULL COMMENT '微信openid',
  `head_img_url` VARCHAR(256) NULL COMMENT '微信头像连接地址',
  `telephone` VARCHAR(32) NOT NULL COMMENT '联系电话',
  `birthday` DATETIME NULL COMMENT '生日',
  `locked` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '用户是否已锁定(默认值:0未锁定)',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '伪删除标记字段',
  PRIMARY KEY (`id`)  COMMENT '主键索引',
  UNIQUE INDEX `username_UNIQUE` (`username` ASC)  COMMENT '用户名唯一索引',
  UNIQUE INDEX `telephone_UNIQUE` (`telephone` ASC)  COMMENT '电话唯一索引')
ENGINE = InnoDB
COMMENT = '用户';

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
